---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 李宇轩.
--- DateTime: 2022/11/24 20:47
---

local key = KEYS[1]; -- 锁的key 如lock:order+userID
local threadId = ARGV[1]; -- 由UUID和当前线程ID拼接的线程唯一标识
local releaseTime = ARGV[2]; -- 超时时间

-- 判断锁是不是自己的
if (redis.call('hexists', key, threadId) == 0) then
    -- 锁不是自己的
    return nil;
end

-- 是自己的锁 则计数器-1
local count = redis.call('hincrby', key, threadId, '-1');

-- 判断计数器是不是为0，如果不为0，更新过期时间
if (count > 0) then
    redis.call('expire', key, releaseTime);
    return nil;
else
    redis.call('del', key);
end
